### ISSUE TITLE
Please enable the "GitHub Discussions" feature

### ISSUE THREAD

**Issue by unforgettableid** [shubhchan/Ruthless-Translation#27]
Dear @shubhchan:

Could you please enable the "GitHub Discussions" feature? People could use it to ask questions, and to get crowd-sourced Ruthless Launcher tech support.

It's quite easy to do.  If you wish to enable the feature, you simply:

* Go to https://github.com/shubhchan/Ruthless-Translation/settings.
* Scroll down.
* Click the green "Set up discussions" button.
* Scroll down again.
* Click the green "Start discussion" button.

Any thoughts?

Thank you for reading this!

**Comment by Davy49** [comment]
I surely agree with your suggestion, at least in my opinion it would be a huge asset for all current users of ruthless launcher.

**Comment by shubhchan** [comment]
Okay, I'll do that

**Comment by shubhchan** [comment]
@unforgettableid @Davy49 it's done.
